name: BTC Tracker Daily

on:
  schedule:
    - cron: '0 8 * * *'  # Tous les jours à 8h UTC (10h France)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v4

    - name: Installer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Installer les dépendances
      run: pip install requests

    - name: Exécuter le script
      run: |
        python btc_price_usd.py
      continue-on-error: true  # Continue même en cas d'erreur pour voir les logs

    - name: Vérifier le fichier généré (optionnel)
      run: |
        if [ -f "prix_btc_usd.txt" ]; then
          cat prix_btc_usd.txt
        else
          echo "Fichier prix_btc_usd.txt non créé."
        fi
