name: BTC Tracker Daily

on:
  schedule:
    - cron: '0 8 * * *'  # Tous les jours à 8h UTC (10h France)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v4

    - name: Installer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Installer les dépendances
      run: pip install requests

    - name: Exécuter le script
      run: |
        ls -la
        python btc_price_usd.py || echo "Script failed with error $?"
      continue-on-error: true

    - name: Vérifier le fichier généré
      run: |
        if [ -f "prix_btc_usd.txt" ]; then
          echo "Contenu de prix_btc_usd.txt :"
          cat prix_btc_usd.txt
        else
          echo "Fichier prix_btc_usd.txt non créé."
        fi

    - name: Committer le fichier
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        file_pattern: prix_btc_usd.txt
        commit_message: "Mettre à jour prix_btc_usd.txt avec les données du $(date +'%Y-%m-%d %H:%M:%S')"
        commit_user_name: "GitHub Action"
        commit_user_email: "action@github.com"
        commit_author: "GitHub Action <action@github.com>"
