name: BTC Tracker Daily

on:
  schedule:
    - cron: '0 8 * * *'  # Tous les jours à 8h UTC (10h France)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v4

    - name: Installer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Installer les dépendances
      run: pip install requests

    - name: Exécuter le script
      run: |
        ls -la  # Vérifie les fichiers
        python btc_price_usd.py || echo "Script failed with error $?"
      continue-on-error: true

    - name: Vérifier le fichier généré
      run: |
        if [ -f "prix_btc_usd.txt" ]; then
          echo "Contenu de prix_btc_usd.txt :"
          cat prix_btc_usd.txt
        else
          echo "Fichier prix_btc_usd.txt non créé."
        fi

    - name: Committer et pousser le fichier
      run: |
        echo "Token masqué : https://xxx@${{ secrets.BTC_TRACKER_TOKEN }}@github.com/VladimirusRex/btc_tracker.git"
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add prix_btc_usd.txt
        git commit -m "Mettre à jour prix_btc_usd.txt avec les données du $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push https://${{ secrets.BTC_TRACKER_TOKEN }}@github.com/VladimirusRex/btc_tracker.git HEAD:main --force || echo "Push failed with error $?"
      env:
        BTC_TRACKER_TOKEN: ${{ secrets.BTC_TRACKER_TOKEN }}
      continue-on-error: true

    - name: Post Installer Python
      run: echo "Post Python setup"
      if: always()

    - name: Post Cloner le dépôt
      run: echo "Post checkout"
      if: always()

    - name: Complete job
      run: echo "Job completed"
      if: always()
